### ISSUE TITLE
2_lazy_collections

### ISSUE THREAD

**Issue by magmel48** [ppopoff/scala-course#2]
а как же вьюхи?

**Comment by ppopoff** [comment]
Вьюхи существуют так же как они и существуют в мире Java. За все время работы со Scala, с вьюхами не сталкиваться. Поэтому я безусловно, считаю что о них стоит рассказать (добавить ссылку в textbook),  а задания не давать

**Comment by ppopoff** [comment]
view решено не включать в первую версию курса
